# Generated by Django 4.0 on 2022-10-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('open_hours', models.CharField(max_length=200)),
            ],
        ),
    ]
