# Generated by Django 4.0 on 2022-10-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='city',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
