# Generated by Django 4.0 on 2022-10-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_shop_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='adress',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
