# Generated by Django 4.0 on 2022-10-11 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_shop_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='adress',
            new_name='address',
        ),
    ]
